version: "3.9"
services:
  # Database
  db:
    image: mysql:8.0
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
    networks:
      - natalie-network
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    env_file: .env
    ports:
      - "8880:80"
    environment:
      PMA_HOST: db
    networks:
      - natalie-network
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      # - wordpress_data_volume:/var/www/html
      - ./wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
    networks:
      - natalie-network
networks:
  natalie-network:
# volumes:
#   wordpress_data_volume: {}